An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
import math
from IPython import display

try:
    import torch
except ModuleNotFoundError:
    %pip install torch
    import torch
from torch import nn
from torch.nn import functional as F
from torch.utils import data

import collections
import re
import random
import os
import requests
import hashlib
import time

np.random.seed(seed=1)
torch.manual_seed(1)
!mkdir figures # for saving plots
------------------

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_3124/2184289921.py in <module>
      5 
      6 try:
----> 7     import torch
      8 except ModuleNotFoundError:
      9     get_ipython().run_line_magic('pip', 'install torch')

~/miniconda3/envs/py37/lib/python3.7/site-packages/torch/__init__.py in <module>
    197     if USE_GLOBAL_DEPS:
    198         _load_global_deps()
--> 199     from torch._C import *  # noqa: F403
    200 
    201 # Appease the type checker; ordinarily this binding is inserted by the

ImportError: /github/home/miniconda3/envs/py37/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so: cannot read file data
ImportError: /github/home/miniconda3/envs/py37/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so: cannot read file data
